MyPet/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyPet.Areas.Identity.Data;
using MyPet.Models;
using MyPet.ViewModels;
using MyPet.ViewModels.DTOs.CartProductForAJAX;
using System.Security.Claims;
using Serilog;

namespace MyPet.Controllers
{
    [Authorize()]
    public class CartController : Controller
    {
        private readonly ProductDbContext _db;
        private readonly UserManager<MyPetUser> _userManager;
        private readonly IMapper _mapper;
        private readonly INotyfService _notifyService;
        public CartController(ProductDbContext db, UserManager<MyPetUser> userManager, IMapper mapper, MyIdentityDbContext userDb, INotyfService notifyService)
        {
           _db = db;
           _userManager = userManager;
           _mapper = mapper;
           _notifyService = notifyService;
           Log.Debug("Controller {@ControllerName} invoked", nameof(CartController));
        }

        [HttpPost]
        public async Task<IActionResult> AddProductToCart(int id)
        {
            string? userId = User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                _notifyService.Information("Авторизуйтесь");
                return RedirectToAction("ShowFilteredProduct", "UserProduct");

            }
            var user = await _userManager.FindByIdAsync(userId!);

            if (!_db.Carts.Any(i => i.UserId == userId))
            {
                await _db.Carts.AddAsync(new MainCart { User = user });
                await _db.SaveChangesAsync();
            }

            var cart = await _db.Carts.SingleOrDefaultAsync(i => i.UserId == userId);

            var products = await _db.Carts
                     .Join(_db.CartProducts,
                         cart => cart.Id,
                         cartProd => cartProd.CartId,
                         (cart, cartProd) => new { Cart = cart, CartProduct = cartProd })
                     .Where(joined => joined.Cart.UserId == userId)
                     .AsNoTracking()
                     .Select(joined => joined.CartProduct)
                     .ToListAsync();

            if (products.Any(p => p.ProductId == id))
            {
                _notifyService.Warning("Этот товар уже добавлен в корзину");
                return RedirectToAction("ShowFilteredProduct", "UserProduct");

            }
            CartProduct cartProduct = new CartProduct()
            {
                Cart = cart,
                ProductId = id,
                Quantity = 1,
            };

            await _db.CartProducts.AddAsync(cartProduct);
            await _db.SaveChangesAsync();
            _notifyService.Success("Успешно добвлено!", 10);

            return RedirectToAction("ShowFilteredProduct", "UserProduct");
        }



        [HttpGet]
        public async Task<IActionResult?> ChosenProducts()
        {
            string? userId = User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (!_db.Carts.Any(cart => cart.UserId == userId))
            {
                return View(new List<ProductAndQuantityViewModel?>());

            }
            
            ICollection<CartProduct?>? productsCarts = await _db.Carts.Include(c => c.CartProducts)
                .Where(id => id.UserId == userId)
                .AsNoTracking()
                .Select(p => p.CartProducts)
                .SingleAsync();

            if (productsCarts is null)
            {
                return View(new List<ProductAndQuantityViewModel?>());
            }
            IEnumerable<int> ProductIds = productsCarts!.Select(i => i!.ProductId).ToList();


            List<ProductAndQuantityViewModel> productViewModels = new();
            productViewModels = await _db.Products.Where(i => ProductIds.Contains(i.Id))
                .Select(p => _mapper.Map<ProductAndQuantityViewModel>(p)).ToListAsync();
            //add quantity from cart

            foreach (var cartProduct in productsCarts)
            {
                foreach (var viewModel in productViewModels)
                {
                    if (cartProduct?.ProductId == viewModel.Id)
                    {
                        viewModel.Quatity = cartProduct.Quantity;
                    }
                }

            }
            return View(productViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeCartData([FromBody] ProductAndQuantityViewModelForAJAX cartProductViewModel)
        {
            string? userId = User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (!ModelState.IsValid)
            {
                _notifyService.Warning($"Что-то пошло не так");
                return BadRequest(ModelState);
            }
            var products = await _db.Carts
            .Join(_db.CartProducts,
                cart => cart.Id,
                cartProduct => cartProduct.CartId,
                (cart, cartProduct) => new { Cart = cart, CartProduct = cartProduct })
            .Where(joined => joined.Cart.UserId == userId)
            .Select(joined => joined.CartProduct)
            .ToListAsync();

            foreach (var product in products)
            {
                foreach (var cartProduct in cartProductViewModel.cartProducts)
                {
                    if (product.ProductId == cartProduct.Id)
                    {
                        product.Quantity = cartProduct.Quantity;
                    }
                }
            }
            _db.CartProducts.UpdateRange(products);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(ChosenProducts));
        }

        [HttpPost]
        public async Task<IActionResult> ExplodeFromCart(int ProductId)
        {
            string? UserId = User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            await _userManager.FindByIdAsync(UserId);

            await _db.Carts.FirstOrDefaultAsync(id => id.UserId == UserId);

            await _db.CartProducts.Where(cp => cp.ProductId == ProductId).ExecuteDeleteAsync();
            await _db.SaveChangesAsync();
            _notifyService.Success("Успешно удалено");
            return RedirectToAction(nameof(ChosenProducts));
        }
        public async Task<IActionResult> ClearCart()
        {
            string? userId = User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            ICollection<CartProduct?>? productsCarts = await _db.Carts.Include(c => c.CartProducts)
               .Where(id => id.UserId == userId)
               .AsNoTracking()
               .Select(p => p.CartProducts)
               .SingleAsync();

            if (productsCarts is null)
            {
                _notifyService.Information("Ваша корзина и так пуста");
                return RedirectToAction(nameof(ChosenProducts));
            }

            _db.CartProducts.RemoveRange(productsCarts!);
            await _db.SaveChangesAsync();
            _notifyService.Success($"Корзина товара очищена. Очещено товаров: {productsCarts.Count}");
            return RedirectToAction(nameof(ChosenProducts));

        }

    }
}

MyPet/Controllers/NewsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyPet.Models;
using MyPet.ViewModels.DTOs.News;
using Serilog;

namespace MyPet.Controllers
{
    [Authorize(Roles = "admin")]
    public class NewsController : Controller
    {
        private readonly ProductDbContext _db;
        private readonly IMapper _mapper;

        public NewsController(ProductDbContext db, IMapper mapper)
        {
            _db = db;
            _mapper = mapper;
            Log.Debug("Controller {@ControllerName} invoked", nameof(NewsController));
        }


        public async Task<IActionResult> ManageNewsSettings()
        {   
            var newSettings = await _db.NewsApiSettings.FirstOrDefaultAsync();
            var settingsViewModel = _mapper.Map<NewsSettingsViewModel>(newSettings);
            return View(settingsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ManageNewsSettings(NewsSettingsViewModel? newsSettings, string? sources,
            string? domains)
        {
            if (newsSettings is null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (sources is not null)
                newsSettings.Sourses = sources;

            if (domains is not null)
            {
                newsSettings.Domains = domains;
            }

            newsSettings.DateTo ??= DateTime.UtcNow;
            NewsApiSettingsModel? toUpdate = new();
            if (!_db.NewsApiSettings.Any())
                await _db.NewsApiSettings.AddAsync(_mapper.Map<NewsApiSettingsModel>(newsSettings));
            else
            {
                int id = await _db.NewsApiSettings.Select(x => x.Id).FirstAsync();
                toUpdate = _mapper.Map<NewsApiSettingsModel>(newsSettings);
                toUpdate.Id = id;
                _db.NewsApiSettings.Update(toUpdate);
            }

            await _db.SaveChangesAsync();
            Log.Information("News settings was changed: {@NewsSettings}", toUpdate);
            return RedirectToAction("Index", "Home");
        }
    }
}

MyPet/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using MyPet.Areas.Identity.Data;
using MyPet.ViewModels;

namespace MyPet.Controllers
{
   
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<MyPetUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<MyPetUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            MyPetUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    FirstName = user.FirstName,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            MyPetUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

MyPet/Views/Shared/_Layout.cshtml
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewBag.Title - Товары онлайн</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MyPet.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/custombtn.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/news.css" asp-append-version="true"/>
</head>

<body>
<header style="z-index: 1000; margin-bottom: 4rem">

    <nav class="navbar navbar-dark navbar-expand-xl bg-dark" style="backdrop-filter: blur(20px)">
        <div class="container-fluid" bis_skin_checked="1">
            <a class="navbar-brand nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                <strong class="badge bg-body-tertiary  text-dark border-secondary-subtle p-2">ВЕБ-ПРИЛОЖЕНИЕ ПО ПРОДАЖЕ ТЕХНИКИ</strong>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    @*Product for user*@
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="AllNews">Новости</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="UserProduct" asp-route-PageNumber="1" asp-action="ShowFilteredProduct">Товары</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Cart" asp-action="ChosenProducts">Корзина</a>
                    </li>

                    @*Product manage*@
                    <li class="nav-item dropdown">
                        <a class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Управление</a>

                        <div class="dropdown-menu" bis_skin_checked="1">
                            <a class="text-dark dropdown-item" asp-controller="Product" asp-action="ProductsToList">Список продуктов</a>
                            <a class="text-dark dropdown-item" asp-controller="Product" asp-action="Create">Создать</a>
                            <div class="dropdown-divider" bis_skin_checked="1"></div>
                                <a class="text-dark dropdown-item" asp-controller="News" asp-action="ManageNewsSettings">Новости</a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Упавление доступом</a>
                        <div class="dropdown-menu" bis_skin_checked="1">
                            <a class="text-dark dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Роли</a>
                            <a class="text-dark dropdown-item" asp-area="" asp-controller="Role" asp-action="Create">Создать роль</a>
                            <div class="dropdown-divider" bis_skin_checked="1"></div>
                        </div>
                    </li>

                </ul>
                @*Search*@
                <div class="d-flex">
                    <input form="searchForm" class="form-control me-2" name="searchTerm" type="search" placeholder="Введете текст...">
                    <button form="searchForm" class="btn btn-outline-light" type="submit">Поиск</button>

                </div>
                <partial name="_LoginPartial"/>

                <form id="searchForm" style="" role="search" asp-controller="UserProduct" asp-action="SearchProduct">
                </form>
            </div>

        </div>
    </nav>

    @if (ViewBag.Title != null)
    {
        <section id="page-title" class="bg-overlay shadow-lg" style="display: flex; min-height: 30dvh; height: auto; z-index: -1">
            <div class="container clearfix px-sm-3 px-3 px-lg-4 px-xl-3" style="justify-content:flex-start;">
                <h1 class="text-light">@ViewBag.Title</h1>
                <div class="row">
                    <span class="col-lg-1 badge text-light shadow-lg" style="display: flex; margin-left: 9px; width: auto; backdrop-filter:blur(10px) saturate(5)">@ViewBag.Secondary</span>
                </div>
            </div>
        </section>
    }

</header>
<div class="container pb-5">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<div class="border-top container mt-5" bis_skin_checked="1">
    <footer class="py-5 pb-2 mb-2">
        <div class="row" bis_skin_checked="1">
            <div class="col-6 col-md-2 mb-3" bis_skin_checked="1">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3" bis_skin_checked="1">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3" bis_skin_checked="1">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3" bis_skin_checked="1">
                <form id="searchForm" style="" role="search" asp-controller="UserProduct" asp-action="SearchProduct">
                    <h5>Найдете все что угодно!</h5>
                    <p>Огромный выбор и <a class="link-primary" asp-action="ShowFilteredProduct" asp-controller="UserProduct">удобные фильтры</a>. Начните прямо сейчас</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2" bis_skin_checked="1">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" name="searchTerm" type="search" class="form-control" placeholder="Ваш запрос">
                        <button class="btn btn-primary" type="submit">Поиск</button>
                    </div>
                </form>

            </div>
        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top" bis_skin_checked="1">
            <p>© 2024-2030 ВЕБ-ПРИЛОЖЕНИЕ ПО ПРОДАЖЕ ТЕХНИКИ, Inc. Все <a asp-action="Privacy" asp-controller="Home">права</a> защищены.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#twitter"></use>
                        </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#instagram"></use>
                        </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#facebook"></use>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</div>


<script src="~/js/three.min.js"></script>
<script src="~/js/vanta.cells.min.js"></script>
<script>
        VANTA.CELLS({
            el: "#page-title",
            mouseControls: true,
            touchControls: true,
            gyroControls: false,
            minHeight: 200.00,
            minWidth: 200.00,
            scale: 1.00,
            color1: 0x00002f,
            color2: 0xd9d9d9,
            size: 1.30,
            speed: 2.90
        })
    </script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/_js/bootstrap.bundle.min.js"></script>

@await Component.InvokeAsync("Notyf")
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyPet/Views/Shared/_OtherScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>

MyPet/Views/Shared/_ProductListForUserPartial.cshtml
@using System.Security.Claims;
@using MyPet.ViewModels;
@model ProductsAndFilterViewModel;
@foreach (var item in Model.Products!)
{
    <div class="card mb-lg-3 rounded-4 mb-4 shadow-sm" href="" style="max-width: 100%; padding: 15px">
        <div class="row">
            <div class="col-md-4 mycenter">
                <img src="@item.MainFilePath" heigth="200px" style="padding: 20px" class="img-fluid rounded-start" value="@item.ProductFullName" asp-append-version="true">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">@item.ProductFullName</h5>
                    <p class="card-text">@item.ShortDescription</p>

                    <p><small class="text-muted"> <mark class="mark text-light bg-dark rounded-3 p-1">@item.ProductType</mark></small> </p>

                    <p class="card-text">От @Math.Round((decimal)item.MinPrice!, 0) BYN </p>

                    <div class="d-flex me-2">
                        <a class="btn btn-primary me-2" style="" asp-controller="UserProduct" asp-action="ViewDetails" asp-route-Id="@item.Id">
                            <div class="mycenter">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-binoculars" viewBox="0 0 16 16">
                                    <path d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z" />
                                </svg>&thinsp;Детали
                            </div>
                        </a>
                        <button form="AddToCart_@item.Id" type="submit" class="btn btn-outline-success">
                            <div class="mycenter">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                                    <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z" />
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                                </svg>&thinsp;Добавить
                            </div>
                        </button>
                    </div>

                    <form asp-controller="Cart" id="AddToCart_@item.Id" asp-action="AddProductToCart">
                        <input type="hidden" value="@item.Id" name="id">
                    </form>
                </div>
            </div>
        </div>
    </div>


}